[package]
name = "netindex-fuzz"
version = "0.0.0"
edition = "2021"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
netindex = { path = "..", features = ["simd", "shared-values"] }

[[bin]]
name = "read"
path = "fuzz_targets/read.rs"
test = false
doc = false
bench = false

[[bin]]
name = "encode"
path = "fuzz_targets/encode.rs"
test = false
doc = false
bench = false

[[bin]]
name = "values"
path = "fuzz_targets/values.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
